### ISSUE TITLE
Accessories not visible in some HomeKit apps

### ISSUE THREAD

**Issue by jamesw4** [jchnlemon/homebridge-telldus#31]
The accessories don't appear to be getting a service name set, this is causing them to not appear in some HomeKit apps (latest version of Eve for example). See https://github.com/nfarina/homebridge/commit/efc570e5a9abfd252b70ace2a154c2360595f4cb

Tried having a tinker myself but no joy. 

Thanks

**Comment by mifi** [comment]
Can you try to install my fork? I added name to service

npm install -g git+https://github.com/mifi/homebridge-telldus.git

**Comment by jamesw4** [comment]
Thank you very much :) installed and all telldus devices now displaying as expected.

**Comment by MatsA** [comment]
Thanks for the update, worked for me to, Mats

**Comment by Formpartner** [comment]
Would this also be applicable when I have upgraded from the TellstickNet to TELLSTICK ZNET LITE VER 2? Since the upgrade all my nexa/telldus and others don't show up. Well they show under unknown accessories, but in Home-app they have "not supported". Strange. Or do you think this is on the Telldus side? Thanks!

**Comment by mifi** [comment]
released in npm, 0.0.6
